default:
  image: registry1.dso.mil/ironbank/opensource/nodejs/nodejs24:24-slim
cache:
  paths:
    - src/node_modules/
pages:
  image: registry1.dso.mil/ironbank/opensource/nodejs/nodejs24:24-slim
  stage: deploy
  script:
    - cd src
    - npm ci
    - npm run check
    - mkdir -p ../public
    - cp -fr dist/* ../public/
  artifacts:
    paths:
      - public
  only:
    - main
